# Generated by Django 3.2.12 on 2024-10-18 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20241018_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'semtler',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'verbose_name': 'Neighborhood', 'verbose_name_plural': 'Neighborhoods'},
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='district',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='postal_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.neighborhood'),
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='shop.city'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.city'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.district'),
        ),
        migrations.AlterModelTable(
            name='city',
            table='iller',
        ),
        migrations.AlterModelTable(
            name='district',
            table='ilceler',
        ),
        migrations.AlterModelTable(
            name='neighborhood',
            table='mahalleler',
        ),
        migrations.DeleteModel(
            name='Mahalle',
        ),
        migrations.AddField(
            model_name='area',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='shop.district'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='shop.area'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.area'),
        ),
    ]
