# Generated by Django 3.2.12 on 2024-10-18 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20241018_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='district',
            field=models.ForeignKey(db_column='ilce_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='shop.district'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(db_column='semt_adi', max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_column='il_adi', max_length=20),
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(db_column='il_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='shop.city'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(db_column='ilce_adi', max_length=20),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='area',
            field=models.ForeignKey(db_column='semt_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='shop.area'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(db_column='mahalle_adi', max_length=90),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='postal_code',
            field=models.CharField(db_column='posta_kodu', max_length=5, null=True),
        ),
    ]
