# Generated by Django 3.2.12 on 2024-10-18 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20241018_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='area',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='city',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='city',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='district',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='district',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='shop.city'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='shop.city'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='shop.district'),
        ),
        migrations.AlterField(
            model_name='area',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='postal_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterModelTable(
            name='area',
            table='semtler',
        ),
        migrations.AlterModelTable(
            name='city',
            table='iller',
        ),
        migrations.AlterModelTable(
            name='district',
            table='ilceler',
        ),
        migrations.AlterModelTable(
            name='neighborhood',
            table='mahalleler',
        ),
    ]
