# Generated by Django 3.2.12 on 2024-10-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20241018_1350'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table=None,
        ),
        migrations.AlterModelTable(
            name='city',
            table=None,
        ),
        migrations.AlterModelTable(
            name='district',
            table=None,
        ),
        migrations.AlterModelTable(
            name='neighborhood',
            table=None,
        ),
    ]
