# Generated by Django 3.2.12 on 2024-10-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20241018_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='city',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='area',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='city',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='district',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_area',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_district',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_neighborhood',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Neighborhood',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
