# Generated by Django 3.2.12 on 2024-10-18 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20241018_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_area',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_district',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_neighborhood',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.area')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.city')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.district')),
                ('neighborhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.neighborhood')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='shop.userprofile')),
            ],
        ),
    ]
