# Generated by Django 5.1.2 on 2024-10-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_cart_cartitem_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_infinite',
            field=models.BooleanField(default=False),
        ),
    ]
