# Generated by Django 5.1.2 on 2024-10-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_orderstatus_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentoption',
            name='parameters',
            field=models.JSONField(default=list),
        ),
    ]
